### PR TITLE
Upgraded to xterm.js 4.2.0

### PR DESCRIPTION
**Pull request by treydempsey**
I saw a bug request asking for an upgrade to xtermjs.

xterm.js 4.x has significant rendering improvements over 3.x, specifically around wide characters.

There are also some other rendering bugs that have been corrected.

Additionally there's a webgl renderer that might offer performance improvements over the standard canvas renderer. I did not include the webgl add on in this PR, but adding it would be trivial.

I've upgraded xterm.js to 4.2.0. The API has changed somewhat but my initial testing seems to indicate that I got all the changes needed in place.

All tests continue to pass.

I hope someone finds this useful. I know it was useful for me.

(edit) removed language that was unproductive and not entirely accurate.

### CODE REVIEW

**Comment by huashengdun** [comment]
Can you provide me with the URLs of your `xterm.min.js` and `xterm-addon-fit.min.js` so that I can verify them?

**Comment by treydempsey** [comment]
The xterm.js developers don't provide download links for the minified xterm.js. Also the versions on cdnjs.com are old.

What I did (and you can do to verify i didn't modify the JS) was clone the xterm.js repo and switch to the v4.2.0 tag.

Follow the instructions in the repo to install the dependencies using npm and build the code.

To create minified versions do:

$ npm run package

Which will use webpack to create lib/xterm.js

To minify the fit addon I did:

$ cd addons/xterm-addon-fit
$ ../../node_modules/.bin/webpack

You can then diff those against my version and see they are the same.

**Comment by huashengdun** [comment]
Hi,

I tried to build xterm.js by following this tutorial https://xtermjs.org/docs/guides/download/#clone-the-git-repository.
But unfortunately it failed.

Can you provide us with a more detailed tutorial on how to build xterm.js?
So that everyone can follow your tutorial to build xterm.js and verify it.
By the way I use Ubuntu 18.04.

**Comment by treydempsey** [comment]
These are the exact steps I used to build the code from a fresh repo. I'm using ubuntu 18.04 LTS, nodejs v8.10.0, npm 3.5.2.

```bash
$ git clone https://github.com/xtermjs/xterm.js.git
$ cd xterm.js
$ git checkout 4.2.0
$ npm install
$ yarn
$ npm run package
$ cd addons/xterm-addon-fit
$ ../../node_modules/.bin/webpack
```

Output is in lib/ and addons/xterm-addon-fit/lib.

**Comment by huashengdun** [comment]
Thanks for your instruction.
I've successfully built xterm.js and xterm-addon-fit.min.js.
Also I've compared their sha1 results with the sha1 results of yours and they all match.
Thanks for your pr.

**Pull request merged**
