### PR TITLE
humble contributions

### PR DESCRIPTION
**Pull request by reimarstier**
hi, i like your project and want to give some feedback:

- When running webssh behind a proxy the X-Real-IP field is currently not used by tornado. This is fixed by addding xheaders=True and a list of trusted proxies.
- Currently most of the logs do not contain the remote ip address. This is necessary to prevent ddos and abuse with e.g. fail2ban.
- Added access control to be able to restrict ssh access to only a few hosts (see security.acl).

### CODE REVIEW

**Comment by huashengdun** [comment]
Lastly for the simplicity, I will not consider for merging 'docker stuff' pull requests for right now.

**Comment by reimarstier** [comment]
The listen address "0.0.0.0" is necessary in the docker environment. Otherwise it will not be accessible at all. But you are right it should be mentioned not to expose that port on the host and to have something like nginx or traefik in front of it (which is the trusted proxy).

About the known_hosts file. I haven't thought of it in that way before. I guess you had the access restriction feature all along.

About the docker stuff: I see your point but it is so convenient just to say 'docker run imagename'. 

But alright then it comes down to just including the real IP address everywhere and I'll be happy.

**Comment by huashengdun** [comment]
Also I this app needs a entry point function main.
otherwise it will not work for the pypi package.

**Comment by huashengdun** [comment]
Also this app needs a entry point function main.
Otherwise it will not work for the pypi package.

**Comment by reimarstier** [comment]
Okay, I have revised my commits. One of the tests is still failing only for python 3.5. Do you have any idea why?

**Comment by huashengdun** [comment]
Hi reimarstier,

You can ignore build errors if they are EOF errors. 
This app doesn't use docker right now, so I think it doesn't need to change setup.py.
Also for the simplicity,  I think we can just use logging methods to log the messages.

**Comment by reimarstier** [comment]
Without the wrapper method the log messages will get quite long. It's not nice but it avoids redefining the remote address everywhere. Do you have a better suggestion?

**Comment by huashengdun** [comment]
I usually update this app from github by running 
```bash
pip install -U https://github.com/huashengdun/webssh/archive/master.zip
```
or

```bash
git clone https://github.com/huashengdun/webssh.git
pip install -U ./webssh
```

So what is the benefit of the modification of setup.py?

**Comment by reimarstier** [comment]
Ah, okay. I was running: `python setup.py sdist install`
This is the setuptools way of installing things.

**Comment by huashengdun** [comment]
Since we let tornado handler the remote_ip, so we can get real client addr by accessing self.remote_ip directly .   
And we still need the value of remote_port, so we can try to get it from the header X-Forwarded-Port | X-Real-Port.
If got no value, then we can get it from self.stream.socket.getpeername() or self.request.connection.stream.socket.getpeername().

**Comment by huashengdun** [comment]
> Well, I think the changes in setup.py are required if you want to be able to install the most current version of webssh from github. The import in setup.py implies that webssh is already installed.
> 
> There are a few other approaches on how to avoid the import:
> https://stackoverflow.com/questions/2058802/how-can-i-get-the-version-defined-in-setup-py-setuptools-in-my-package
> 
> So it's not just about docker.

https://stackoverflow.com/questions/458550/standard-way-to-embed-version-into-python-package

**Comment by huashengdun** [comment]
Hi reimarstier,
I have just made a commit to let tornado parse xheaders as you suggested previously.

**Comment by huashengdun** [comment]
I am going to close this pull request as I have added "xheaders" to this app by myself.
And thanks for your suggestion, reimarstier.

**Pull request closed without merging**
